// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mansaa_app/features/my_courses/data/models/student_courese_response/student_courese_response.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(StudentCourseResponseAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(StudentCourseResponseAdapter());
  }
}
